### ISSUE TITLE
Mistake in GETTINGSTARTED.md

### ISSUE THREAD

**Issue by tadam98** [BSI-OFIQ/OFIQ-Project#1]
https://github.com/BSI-OFIQ/OFIQ-Project/blob/develop/doc/GETTINGSTARTED.md
`Create and build the project: go to <OFIQ-PROJECT>\scripts\ directory and run 02_build_FaceQAlib.cmd` is not correct there are two scripts with different names:
```
02_configure_and_build_FaceQAlib.cmd
03_build_FaceQAlib.cmd
```

I executed both.
Please update the procedure.

Best,
Mickey Cohen

**Comment by m-schaubert** [comment]
I have updated the [GETTINGSTARTED.md](https://github.com/BSI-OFIQ/OFIQ-Project/blob/develop/doc/GETTINGSTARTED.md) guide.
