### ISSUE TITLE
Models not available

### ISSUE THREAD

**Issue by seba-eng** [BSI-OFIQ/OFIQ-Project#12]
The link to the ISO portal returns a 404. 
https://standards.iso.org/iso-iec/29794/-5/ed-2/en/OFIQ-MODELS.zip 
I'm not sure if the link is incorrect or if there is a problem at the ISO.

**Comment by veriditin** [comment]
It looks like the models are available from:

https://standards.iso.org/iso-iec/29794/-5/ed-1/en/OFIQ-MODELS.zip

and then the test images from:

https://standards.iso.org/iso-iec/29794/-5/ed-1/en/OFIQ-IMAGES.zip

**Comment by m-schaubert** [comment]
@seba-eng As a temporary solution, you could modify the URLs in CMakeLists.txt in the root folder, just change the 'ed-2' to 'ed-1' in the rows 52 and 66. The URLs mentioned by @veriditin (thanks for that) are working fine at the moment. We'll check that issue.

**Comment by bbtams** [comment]
https://standards.iso.org/iso-iec/29794/-5/ed-2/en/OFIQ-MODELS.zip
and
https://standards.iso.org/iso-iec/29794/-5/ed-2/en/OFIQ-IMAGES.zip
are the links that should be used. The files have been placed (falsely) in the 'ed-1' space. They will be moved, soon.

**Comment by veriditin** [comment]
Ok, good to know! I changed the lines as suggested by @m-schaubert. Will you let us know in this thread when the models&images are moved to the `ed-2` space @bbtams ?

**Comment by bbtams** [comment]
@veriditin: Yes, I will wait for the models being moved, let you know, and then close the issue.

**Comment by bbtams** [comment]
We discussed this out with ISO and the non-temporary links are in fact
https://standards.iso.org/iso-iec/29794/-5/ed-1/en/OFIQ-MODELS.zip
https://standards.iso.org/iso-iec/29794/-5/ed-1/en/OFIQ-IMAGES.zip
They have been adjust in both (develop and main branch).
Enjoy :-)
