### ISSUE TITLE
`pip` rather than `snap` as recommended cmake installation tool

### ISSUE THREAD

**Issue by veriditin** [BSI-OFIQ/OFIQ-Project#13]
Section 1.3.1 of the build guide mentions that in order to install cmake, one should use `snap`:

```
To install cmake (in a version 3.26 or higher) use `snap` (and not `apt`) as follows.

$ sudo snap install cmake --classic
```

Probably because, as of this writing, the version that is available on `apt` is <3.26, whereas >=3.26 is required to build this project.

However, snap is a ubuntu-specific tool which is not available on all distributions, nor even on the official ubuntu docker image.

My suggestion would be to use pip to install `cmake` (as well as `conan`) and update the guide accordingly.

**Comment by bbtams** [comment]
Thank you. Yes, in fact it is important that CMake version >= 3.26 is used and it is not important to install it via snap. The documentation states that the procedure has been tested with Ubuntu (22.04) and the installation via snap is one possible (but not the only one) way to go. Note, we will test OFIQ with further platforms and extend the documentation before publishing the final release.
