### ISSUE TITLE
Not sure how to decide which image is good

### ISSUE THREAD

**Issue by tadam98s** [BSI-OFIQ/OFIQ-Project#16]
[table.xlsx](https://github.com/BSI-OFIQ/OFIQ-Project/files/14668602/table.xlsx)
![2021-MickeyCohen](https://github.com/BSI-OFIQ/OFIQ-Project/assets/159139709/72ea57ba-da50-4617-a0e4-e0ff115d6d09)
All the images habe UQS ~ 27.
Please include the "perfect image" in the test set.

Also, you are using the German convention of ";" while the default elsewhere is "," **Comma** Separated Values. Can you add a parameter to set it. You can keep the ";" as default.

It looks good. I will study it in depth.
Thank you for adding the "all images" option.

Best,
Mickey

**Comment by bbtams** [comment]
Hi Mickey, 

I suppose you only looked at the UnifiedQualityScore column which is the native quality measure; you should inspect the colum UnifiedQualityScore.scalar where you can find the quality component measure between 0 (worst) and 100 (best). I don't think there is such a thing as the "perfect image" among real ones.

We used the ";" to enable loading of the CSV file with Excel; I am not sure if this only because this is German convention. I can create a ticket for integrating configuration of the CSV separation character, but this will have low priority as it only affects the sample application (and not the OFIQ library).

Thank your for studiying OFIQ in depth; any improvement suggestion would be helpful.

Best,
Benjamin

**Comment by tadam98s** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    Hi,
    
      
    Same question which threshold indicates "take
        the face it meets 17974-5 requirements".
    
      
    B-01 with smile gets 65 - smile is not
        permitted
    B-02 rolled gets 65 -
        strong roll is not allowed
    B-09 Background gets 67 - background is not
        allowed
    C-01 gets 77 but head is too small compared
        with the standard (Which parameter gives the eye distance? Is it
        >> 90?)
    C-06 glasses get 53 - occlude the eyes I think
        it should be lower
      
    C-07 two faces gets 82 - but two faces not
        allowed
    C-10 Background gets 86 - background is not
        allowed and also face is too small. (Which parameter gives eye
        distance in pixels ?)
    R-02 rolled gets 71 - strong roll is not
        allowed
    R-04 eyes closed head covered 78 - both not
        allowed
    R-07 scarf gets 56 - chin is not visible I
        would prefer a lower score.
      
    R-09 Background gets 83 - background is not
        allowed and also face is too small. (Which parameter gives eye
        distance in pixels ?)
    
    
    
      
      body p { margin-bottom: 0cm; margin-top: 0pt; } 
      
      Best regards,
       Mickey Cohen
       Shanit Ltd.
       CEO
       POB 23410, Jerusalem 9123302, Israel
        Schedule a meeting
        (M) +972-54-758-6312
       Skype: tadam_98 
       ***@***.***
       
    On 21/03/2024 9:23 AM, bbtams wrote:
    
    
      
      Hi Mickey,
      I suppose you only looked at the UnifiedQualityScore
        column which is the native quality measure; you should inspect
        the colum UnifiedQualityScore.scalar where you can find the
        quality component measure between 0 (worst) and 100 (best). I
        don't think there is such a thing as the "perfect image" among
        real ones.
      We used the ";" to enable loading of the CSV file
        with Excel; I am not sure if this only because this is German
        convention. I can create a ticket for integrating configuration
        of the CSV separation character, but this will have low priority
        as it only affects the sample application (and not the OFIQ
        library).
      Thank your for studiying OFIQ in depth; any
        improvement suggestion would be helpful.
      Best,
        Benjamin
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you authored the thread.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/BSI-OFIQ/OFIQ-Project/issues/16#issuecomment-2011366512",
"url": "https://github.com/BSI-OFIQ/OFIQ-Project/issues/16#issuecomment-2011366512",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
  

--------------1jKwxgYezhBCiNfc2WH8HUwI
Content-Type: image/jpeg; name="0eW82mw1VPEtnBp9.jpg"
Content-Disposition: inline; filename="0eW82mw1VPEtnBp9.jpg"
Content-Id: 
Content-Transfer-Encoding: base64

/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAIBAQIBAQICAgICAgICAwUDAwMDAwYEBAMFBwYH
BwcGBwcICQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQICAgMDAwYDAwYMCAcI
DAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wAAR
CAAMAAwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAA
AgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkK
FhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWG
h4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl
5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREA
AgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYk
NOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOE
hYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk
5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD79PxatfG3wvj1jSxqOpeJLPUJE1tUYzP5
UpBgmEYy20sShYA4f72NyVgaX+1xqvhSOWzs9UvtPVJW82FZWj2SDhgV7EYwQeeK+afi5daj
+zN+0/4lsvB+taxpcnhjVJ7awu1uSLhEDYwzAAMMcEEYIHIPNfU37Gn7Jeg/tvfDTU/iF8Qt
W8Sal4o1PWJobm5guo7dZBHHEF+RY9o444AHA4r+NsDXxGPxX1fBy9niYe7J3tCSjo5cy97m
k7XTi7u8m9bH8K5dxBmGZ4v6ngpezxdO8ZO7UJKGjkpJc/M3a6cWm7yck3Y//9k=
--------------1jKwxgYezhBCiNfc2WH8HUwI
Content-Type: image/jpeg; name="pbWUC04vBQSqgE1h.jpg"
Content-Disposition: inline; filename="pbWUC04vBQSqgE1h.jpg"
Content-Id: 
Content-Transfer-Encoding: base64

/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAIBAQIBAQICAgICAgICAwUDAwMDAwYEBAMFBwYH
BwcGBwcICQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQICAgMDAwYDAwYMCAcI
DAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wAAR
CAAMAAwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAA
AgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkK
FhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWG
h4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl
5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREA
AgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYk
NOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOE
hYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk
5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD7S+Fn7YPh/wCKVt8QLe6gjnuvAfgTWPF0
0i3TBp3smjwpVDny9sqhsDcWBIYZAr55T/go6/iK+vLjRF1nTdPMiqsCyNtVxGm8gkglS24j
PIGASSM15PBrmqfs6/Enx9Y+E9QWxh1d77w/qDXGnWV619YNMyyW7+fC48uQKvmIoCvtXcDt
XHo37Hf7J/hv4m/DTUL6+utYhlg1SS2VbeWMKVEMLZO6NjnLHv6V/Qb4NwuGjKvU1i7cuuvn
dbLXazfyPyZcRV60o0oaSV7/AKWe/wCB/9k=
--------------1jKwxgYezhBCiNfc2WH8HUwI
Content-Type: image/jpeg; name="LUcLHC81mrGbmggP.jpg"
Content-Disposition: inline; filename="LUcLHC81mrGbmggP.jpg"
Content-Id: 
Content-Transfer-Encoding: base64

/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAIBAQIBAQICAgICAgICAwUDAwMDAwYEBAMFBwYH
BwcGBwcICQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQICAgMDAwYDAwYMCAcI
DAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wAAR
CAAMAAwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAA
AgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkK
FhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWG
h4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl
5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREA
AgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYk
NOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOE
hYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk
5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD78/Y9/Y/0fxv4Q1jxP4o1jwv4iuPEOhy6
hDDf3H+maVc5z9onySdmWJLMcEFSQc8eAfFfSvEn7LHjGbwvo3jq7urUxpeNPomoSw2kzuME
jY+GYBQCfVcdqTSvitrH7LPxJ8daP4Xkha1uZ7rRJmvIhNJLbJK6bSRgAsAMkAHI4xXd/sif
sieG/j58Nr7WNYvtctbq21OSzVbKaJIyixROCQ0bHOZD3xjHFfxHmmNwGKyrCYPL8P7KvHnv
PnfR+9qtZcz1974do6H9p5fhMbhMzxeNzHEe1oS5LQ5I9V7uj0jyLT3W+bd6n//Z

--------------1jKwxgYezhBCiNfc2WH8HUwI--

**Comment by bbtams** [comment]
Hi Mickey,
OFIQ implements what is specified in ISO/IEC 29794-5 (which is currently at DIS level). UQS is based on MagFace. MagFace does not necessarily check conformance but the mere utility of the image for being recognizable.
Best,
Benjamin
