### ISSUE TITLE
Inconvenience at GETTINGSTARTED.md

### ISSUE THREAD

**Issue by tadam98** [BSI-OFIQ/OFIQ-Project#2]
https://github.com/BSI-OFIQ/OFIQ-Project/blob/develop/doc/GETTINGSTARTED.md
`pip install conan==1.59` assumes one has some python installed on Widnows.
Following this install, the PATH has to be updated to point to:
`set PATH=%PATH%;C:\Users\mickey\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts ` which is ... ugly.
https://conan.io/downloads.html only allows windows install of the latest version.
Please provide instruction for windows installation of the required 1.59 version without pip.

Thanks,
Mickey Cohen

**Comment by m-schaubert** [comment]
Using Python and pip is the recommended way to install conan, and if you need some specific, not the latest, version the only way to install it. The windows binaries are provided by conan only for the latest version.
The ugly python-Path is not the issue of this project, but you could try to install Python to some other folder, like C:\Python39, or maybe let the Python installer set the path variable for you, so you don't have to do it manually.
