### ISSUE TITLE
lapack missing in conan dependencies

### ISSUE THREAD

**Issue by alexkrz** [BSI-OFIQ/OFIQ-Project#20]
I am trying to build the project on Ubuntu 20.04 with cmake 3.26.4 and conan 2.0.17.
When I execute `build.sh`, I get an error that LAPACK is missing.
The error results from the file `OFIQlib/CMakeLists.ubuntu.conan.cmake:line26`

Ideally, it would be possible to include lapack in the conanfile.txt.
However, I found out that lapack is currently not provided by conan.
There is the following thread in the conan Repo: https://github.com/conan-io/conan-center-index/pull/15556

Maybe it is possible to find lapack by adding openblas as dependency.
But I haven't succeeded in doing so yet.

**Comment by bbtams** [comment]
Section 1.3 in the documentation describes that one needs to install the following:
$ sudo apt-get install build-essential python3-pip liblapack-dev
I am not sure if this works with Ubuntu 20.04, too (we tested with Ubuntun 22.04).

**Comment by m-schaubert** [comment]
Lapack was removed from ubuntu cmake file
