### ISSUE TITLE
Sharpness Measure Calculation

### ISSUE THREAD

**Issue by hasan-nn** [BSI-OFIQ/OFIQ-Project#22]
Hello,
Great work!

I noticed that the method to calculate Image Sharpness in your repository is different than the method proposed in the original ISO/IEC TR 29794-5:2010 Report.

Can you please share the details of your method?

Thank You

**Comment by JoMe2704** [comment]
All OFIQ algorithms (except Brightness) differ from those defined in ISO/IEC TR 29794-5:2010. 

The algorithm is based on a Random Forest classifier using the following features of an image I:

- Sobel filters. For each of the kernel sizes s=1,3,5,7,9, the isotropic Sobel filter S_s is computed on the pre-processed image using the OpenCV function Sobel() with parameters dx=1, dy=1 and ksize=s. For each s, the arithmetic mean and standard deviation of the absolute values of the outputs in the landmarked region are computed as feature, i.e. μ(|S_s(I)|) and σ(|S_s(I)|) for s=1,3,5,7,9.

- Laplacian filters. First, a Gaussian blur filter with 3x3 kernel is applied to the pre-processed image to remove noise. Then, for each of the kernel sizes s=1,3,5,7,9, the Laplacian Filter L_s with kernel size s is computed on the blurred image using the OpenCV function Laplacian() with parameter ksize=s. For each s, the arithmetic mean and standard deviation of the absolute values of the outputs in the landmarked region are computed as feature, i.e. μ(|L_s(G_3(I))|) and σ(|L_s(G_3(I))|) for s=1,3,5,7,9 where G_3 is the Gaussian blur filter with kernel size 3.

- Difference to mean-filtered image. For each of the kernel sizes s=3,5,7 a mean filter (OpenCV function cv2.blur) is applied to the image and the resulting image is subtracted from the original one. The mean and standard deviation of this difference in the landmarked region are returned as feature value.

This results in a features vector of length 26. 

The algorithm takes as input the image I in BGR colour channel order with 8 bits per channel and the segmentation mask M of the landmarked region (convex hull of all landmarks), and performs the following steps:

1. If the landmarked region protrudes the image region, restrict it to its intersection with the image region.
2. Crop I to the minimal upright bounding box of the landmarked region.
3. Convert I to grey scale. 
4. Extract the 26 features as described above
5. Feed the feature vector f into the Random Forest classifier model to obtain a native quality score x.
6. Compute the quality component value as y = ROUND(100 ∙ (SIGMOID(x,20,10)))

**Comment by hasan-nn** [comment]
Thanks for your quick reply and for the detailed explanation.

> All OFIQ algorithms (except Brightness) differ from those defined in ISO/IEC TR 29794-5:2010.
Is there any detailed report for your **OFIQ algorithms** ?

**Comment by JoMe2704** [comment]
All algorithms will be specified in the upcoming revision of ISO/IEC 29794-5. It will be published next year. Furthermore, a report on the OFIQ development will be published.
