### ISSUE TITLE
Timeline for stable release

### ISSUE THREAD

**Issue by seba-eng** [BSI-OFIQ/OFIQ-Project#26]
Hi OFIQ-Team. Can you tell me the expected date/timeline for the stable 1.0.0 release of OFIQ? The current RC is still work in progress, right?

**Comment by bbtams** [comment]
The next ISO meeting will be in July 2024 where we revise the algorithmic of OFIQ. Then the changes will be implemented to align OFIQ with FDIS (final draft international standard). This will be another release candidate. In 2025 the final international standard will be finished and OFIQ 1.0.0 will be released.

Yet, the RC is work in progress. We are integrating support for different platforms (Ubuntu 24.04, MacOS, iOS, Android) right now.
