### ISSUE TITLE
OFIQ-Project-develop/extern/onnxruntime-win-x64-1.14.1/include non-existent

### ISSUE THREAD

**Issue by tadam98s** [BSI-OFIQ/OFIQ-Project#39]
Hi,

When compiling the latest develoment branch I am getting an error that folder "extern" is missing for onnxruntime.
See attached.
Can you kindly assist ?
(in the mean time I copied the folder from the version I downloaded on 15-May-2024)

Thanks,
Mickey

[build.txt](https://github.com/user-attachments/files/15902913/build.txt)

**Comment by bbtams** [comment]
Hi Mickey, I can reproduce your problem. We will work on this now.

**Comment by bbtams** [comment]
I fixed the problem. Please check, if it works for you. Note that as the ISO 29794-5 changes, OFIQ does. So the output may be different now (slightly for most and heavily for some measures).

**Comment by tadam98s** [comment]
I can confirm that the compilation is now successful.
All tests also pass.
Thank you.ו ?
