### ISSUE TITLE
OpenCV error is back in the latest version

### ISSUE THREAD

**Issue by tadam98s** [BSI-OFIQ/OFIQ-Project#41]
OpenCV error is back in the latest version.  The error dows not happen with my previous download from 2024-05-15.

Also, PLEASE do not abort when there is an error and just write an error line in the CSV for this filename. I am running on thousands of images and it is a nightmare when it aborts due to a missing simple try-catch.
I rever back to the previous version. (I am unable to share the image)

OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.5.5) Error: Image step is wrong (The matrix is not continuous, thus its number of rows can not be changed) in cv::Mat::reshape, file C:\Users\Mickey\.conan2\p\b\openc00b993b028ed5\b\src\modules\core\src\matrix.cpp, line 1176

What is strange is that I saved the image with paint to bmp. closed paint. Opened the bmp and saved as jpg and the error is still there. Image dimetions are 592x500 (widthxheight)

Best,
Mickey

**Comment by m-schaubert** [comment]
Hi Mickey, we've committed a fix for "The matrix is not continuous ..." error, could you please check out and test the latest version using that one "not continuous" image.
Thanks,
Maxim

**Comment by tadam98s** [comment]
You did in the version of 2024-05-15. But what I dowloaded after the latest fix to the installation procedure + MAC ob 2024-06-20 revived the error. So I reverted back to 2024-05-15. Please check the latest version maybe it did not include the correction.

**Comment by m-schaubert** [comment]
It turned out, that we had this issue in two places, and the second place was "activated" with the commit on 2024-06-20. So we fixed that yesterday:
https://github.com/BSI-OFIQ/OFIQ-Project/pull/37/commits/263bef73ac3da469e59c9d27ac09badc17fe5488

**Comment by tadam98s** [comment]
compiling now, will update soon.

best,
mickey
-- 
Mickey Cohen
Shanit Ltd.
CEO
POB 23410, Jerusalem 9123302, Israel
M: +972-54-758-6312
Skype: tadam_98
***@***.***
