### ISSUE TITLE
Some doubts about Ofiq

### ISSUE THREAD

**Issue by Raulr00** [BSI-OFIQ/OFIQ-Project#42]
Hello, I have a few questions:

- I want to try OFIQ with my custom dataset, so I guess I have to use the OFIQSampleApp.exe and change the path.

- I have been trying the OFIQSampleApp.exe with some images and I see something strange in the NoHeadCoverings variable. Some persons that are bald get a score of 0. If I’m correct, this means that this person has their head fully covered.

- Is there any way I can extract the landmarked region of the image using the .exe?

- Do the other quality values have any influence on the final value of the unified quality score?

**Comment by bbtams** [comment]
* OFIQSampleApp is just an example. Consumers of OFIQ are expected to implement their own application using OFIQlib and may find inspiration in the source code of OFIQSampleApp. We will not give support for OFIQSampleApp.
* OFIQ outputs a native/raw score of 0 if no pixels classified as no head coverings. This will be mapped to a quality component value/scalar score of 100. Note, that die mapping of NoHeadCovering to its quality component value/scalar value will likely change after the next ISO comments resolution meeting.
* No, you can't extract landmarks with the sample app without modifying it. The interface of OFIQlib is described in the documentation.
* No, the unified quality score is computed independently from the other quality measures using a MagFace CNN.

**Comment by Raulr00** [comment]
But for example, if in my case I just want to extract all the features of the images in my database following the ISO/IEC 29794-5 standard, do I have to build my own C++ project and take inspiration from the source code of the OFIQSampleApp? I guess the answer is yes, just to confirm.

Thanks for your time and answer.

**Comment by m-schaubert** [comment]
Do you mean face quality measures when you say "extract all the features"? In that case, you can do the following - you just build the OFIQSampleApp without modifying it and run it, then you'll get the output for the measures listed in your config file (by default - `.\data\ofiq_config.jaxn`) in the section `"measures": []`.
If you specify the command line argument `-o`, e.g. `-o ofiq_results.csv`, the results will be written in that file, else they'll be printed out.

**Comment by Raulr00** [comment]
Yes, I referred to the face quality measures. I have already been working with the sample app for about a month, and when I read the documentation, I assumed that you could use the sample app to extract the face quality measures, ensuring you follow the ISO/IEC 29794-5 standard (or you can also build your own project using OFIQlib as bbtams said).

The problem I saw with bald people and the noHeadCoverings, along with my interest in getting the landmarks, led me to write this issue. So, any changes you make to the app will not be reflected in the sample app, right? Then I assume it is much better to build my own project following the sampleApp example to keep my OFIQlib updated.

Thanks for your time!
