### ISSUE TITLE
Problem testing the Linux compilation

### ISSUE THREAD

**Issue by tadam98** [BSI-OFIQ/OFIQ-Project#5]
I have downloaded and compiled the pacges as instructed in https://github.com/BSI-OFIQ/OFIQ-Project/blob/develop/doc/GETTINGSTARTED.md
I am using ubuntu 18.04 wsl2 under Windows 11.

```
The required libraries and package can be install via conan using
$sh 01_conan-install-FaceQAlib.sh
Compile OFIQlib.
$ sh 02_configure_and_build_FaceQAlib.sh
Run the sample program.
$ sh run_sample.sh
[ERROR] initialize() returned error: Undefined error.
FaceDetectionError: failed to initialize opencv SDD face detector
```

[01_conan-install-FaceQAlib.log](https://github.com/BSI-OFIQ/OFIQ-Project/files/12049826/01_conan-install-FaceQAlib.log)
[02_configure_and_build_FaceQAlib.log](https://github.com/BSI-OFIQ/OFIQ-Project/files/12049827/02_configure_and_build_FaceQAlib.log)
[run_ctest.log](https://github.com/BSI-OFIQ/OFIQ-Project/files/12049844/run_ctest.log)

**Comment by bbtams** [comment]
You need to download the CNN models. Specifically for SSD face detector you have to following this guide: https://github.com/BSI-OFIQ/OFIQ-Project/blob/develop/data/models/ssd_facedetect/README.md

**Comment by tadam98** [comment]
Clsed with Issue #4
