### ISSUE TITLE
How can I tur off some metrics that I don't want to use

### ISSUE THREAD

**Issue by sfxnminimah** [BSI-OFIQ/OFIQ-Project#53]
Hello,

Is there an optimized way to remove unnecessary metrics to reduce the overall project size, specifically by stripping off models like the Unified Quality Score (which has a model size of 113MB)?

**Comment by m-schaubert** [comment]
You could simply remove the unnecessary metric from the section `config: measures:` in your config file (`.\data\ofiq_config.jaxn` per default):
```
  "config": {
    "detector": "ssd",
    "landmarks": "ADNet",
    "measures": [
      "HeadPose",
...
      "UnifiedQualityScore",
...
```
Here is the direct link to Unified Quality Score in the default config file: 
https://github.com/BSI-OFIQ/OFIQ-Project/blob/main/data/ofiq_config.jaxn#L31
Also, you **could** (this is not necessary) remove the corresponding section in `config: params:`:
https://github.com/BSI-OFIQ/OFIQ-Project/blob/main/data/ofiq_config.jaxn#L188

And then you can remove the corresponding folder from your `models` directory.

But be careful, most of the models in `\data\models` are required for preprocessing and should not be deactivated and removed, here is the list:
```
\face_detection
\face_landmark_estimation
\face_occlusion_segmentation
\face_parsing
\head_pose_estimation
```
